### ISSUE TITLE
希望增加会客室自动赠送重复线索的功能

### ISSUE THREAD

**Issue by GodofTheFallen** [Konano/arknights-mower#180]
目前当会客室已拥有10个线索且不满足开趴条件时，mower既不会开趴也不会赠送出去重复线索。这种情况下也无法通过自然手段获得新的线索，如果没有好友赠送缺少的线索，就永远无法满足开趴条件而卡住。
MAA的解决方案是线索满10个后强制送走所有未安放在会客室墙上的重复线索

**Comment by Shawnsdaddy** [comment]
重复#159
