### ISSUE TITLE
每次插拔后存在bug

### ISSUE THREAD

**Issue by fearlessxjdx** [Konano/arknights-mower#186]
每次插拔后，总是会把干员换回预设的干员，但其实上一个休息流程都还没完毕呢。

结果就是换回预设干员后，又开始了休息流程。。

我觉得应该保存下插拔前的干员情况，插拔后换回Current。让休息流程结束的时候，由程序自己换回预设。

**Comment by Shawnsdaddy** [comment]
仅插拔模式下功能是阉割的，只能通过博士手动切换排班表了。。

推荐使用动态换班 :)

**Comment by Shawnsdaddy** [comment]
> > 仅插拔模式下功能是阉割的，只能通过博士手动切换排班表了。。
> > 仅插拔模式是在动态换班不完善的时候开发的。在动态换班已经非常成熟的今天并不推荐使用
> 
> 就是动态换班，缺个优化。还有“铅踝”经常找不到人。。

识别应该修复了，尝试用一下最新版本
