### ISSUE TITLE
自动战斗等待计时偶尔会浪费一轮时间

### ISSUE THREAD

**Issue by SiIith** [Konano/arknights-mower#33]
目前自动战斗会自动累计上一轮的等待计时并重设为基础时间（还没看代码，我看日志似乎是这么回事），有时候如果这个时间累计太长的话有几个情况会导致直接浪费一轮。比如下图：
![image](https://user-images.githubusercontent.com/52880557/140453195-61058d06-c65a-4b0a-bbbd-ec1fdfb07110.png)
在本轮结束前的几秒钟开启了新一轮计时，于是便在结算界面又等了190秒。结果下一次计时会把这次等待的时间也计入基础时间，导致每一轮的等待时间会越来越长。这一关原本是90秒就能打完的，但经过了几次叠加之后每一轮要跑190秒。在刷了十几轮之后每一轮基础等待时间已经到270秒了。
![image](https://user-images.githubusercontent.com/52880557/140453716-40afd8ed-985b-4763-ab3b-99206697c723.png)

可不可以固定成每10秒检测一次屏幕（实际上应该占用不了多少资源），或者加一个waiting_time参数让用户自定义等待间隔？

**Comment by SiIith** [comment]
当然其实是小问题，毕竟反正是挂后台，具体是十分钟刷完还是半个小时刷完区别不大。如果你没空搞又觉得需要改的话我可以尝试发个pr（hhh）

**Comment by Konano** [comment]
不太清楚怎么会在结算页面等到 190 秒的？

附上程序的实现逻辑：
https://github.com/Konano/arknights-mower/blob/398c954e2db99740e791712b22a007e0077b2ac3/arknights_mower/solvers/operation.py#L124-L144

**Comment by SiIith** [comment]
我看了几轮，感觉问题可能是OCR会把这个界面也当作作战中，加了几轮wait_total之后才停止继续累计。
![image](https://user-images.githubusercontent.com/52880557/140633340-9645db53-a419-4c47-8f6c-d9484b1e422b.png)
![image](https://user-images.githubusercontent.com/52880557/140633556-23ce6a50-1001-4946-84c6-2ee3b44ef7a6.png)
比如这里其实差不多一分钟前就打完了，因为网络原因卡了一分钟左右，然后time_total直接给干到了100+。如果连续卡了几轮的话时间就会堆到很高，但每轮最多只会-10s（140行）。
如果不用这个预设wait_start而是固定成每10s执行一次get_scene的话会有问题吗？我觉得这个情况在网络差的环境下（主要模拟器网络都不太稳定）还挺容易复现的，可能需要考虑一下。

**Comment by Konano** [comment]
更改作战时等待逻辑：剿灭时每轮等待 60s，普通关卡每轮等待 10s

https://github.com/Konano/arknights-mower/blob/78c81674a65f20c7f48c0d5bf3142b41939b5120/arknights_mower/solvers/operation.py#L134-L145

更改首次等待时长逻辑：每次更新只允许 `wait_start` 最多增加一轮等待时长，防止网络波动所造成的单次作战耗时过多

https://github.com/Konano/arknights-mower/blob/78c81674a65f20c7f48c0d5bf3142b41939b5120/arknights_mower/solvers/operation.py#L147-L152
