### ISSUE TITLE
公开招募无法正确识别获得干员的界面，并卡住

### ISSUE THREAD

**Issue by YuiTH** [Konano/arknights-mower#35]
![image](https://user-images.githubusercontent.com/22416062/140635908-bd464bc4-d79d-4517-967c-88a64706295c.png)
如图所示，公招开包界面后，出现的干员自我介绍界面程序无法正确识别。卡在了这个界面。
版本为arknights-mower-1.3.9，模拟器为NoxPlayer，官服。

**Comment by Konano** [comment]
目前识别干员页面在低分辨率下有点问题，正打算想个办法解决

**Comment by YuiTH** [comment]
> 目前识别干员页面在低分辨率下有点问题，正打算想个办法解决

测试的时候用的是什么分辨率和模拟器能给个参考吗，目前看到好多低分辨率导致的问题。

**Comment by Konano** [comment]
> > 目前识别干员页面在低分辨率下有点问题，正打算想个办法解决
> 
> 测试的时候用的是什么分辨率和模拟器能给个参考吗，目前看到好多低分辨率导致的问题。

测试时候的分辨率是 1080，据反馈 900 也还不错

**Comment by SiIith** [comment]
如果predict的时候只输入右下角四分之一（第四象限）的图像会不会改善一点，可能是因为XX的信物字太小了

**Comment by YuiTH** [comment]
> > > 目前识别干员页面在低分辨率下有点问题，正打算想个办法解决
> > 
> > 
> > 测试的时候用的是什么分辨率和模拟器能给个参考吗，目前看到好多低分辨率导致的问题。
> 
> 测试时候的分辨率是 1080，据反馈 900 也还不错

我之前使用的分辨率就是900，改到1080后正常工作了。
