### ISSUE TITLE
基建换班无法识别新干员

### ISSUE THREAD

**Issue by proItheus** [Konano/arknights-mower#40]
好像耶拉的数据没加，其他的新干员我没有，估计也不行。
`WARNING - 599 - agent - 干员名称识别异常：耶拉 为不存在的数据，请报告至 https://github.com/Konano/arknights-mower/issues`
以及为啥在选干员界面不断左右划啊？如果是为了识别更精确的话一点点想一个方向滑动可以吗？这样的话看起来比较直观……

**Comment by Konano** [comment]
选干员界面不断左右划是因为模拟器有时会抽风滑动漂移，以后估计会尝试优化这个问题
