### ISSUE TITLE
Use github action to auto fetch new agent data from ArknightsGameData character_table.

### ISSUE THREAD

**Issue by YuiTH** [Konano/arknights-mower#43]
We can use Github Action to auto fetch new agent data from [ArknightsGameData](https://github.com/Kengxxiao/ArknightsGameData/blob/master/zh_CN/gamedata/excel/character_table.json). I believe there is a repo update all unpacked data from arknights and update in time.

Is there any data else needs to be update and could fetch from unpacked data?

**Comment by Konano** [comment]
See #76.
