### ISSUE TITLE
[feature] 刷图功能快速识别当前已选关卡

### ISSUE THREAD

**Issue by abc1763613206** [Konano/arknights-mower#80]
当前 `operation` 功能如果不指定关卡参数（如刷活动图时），程序的逻辑为：回到主界面，选择右下角的上一次关卡。     
这样一来，在刷活动图时，必须尝试自行开启一次关卡，一定程度上也提高了时间成本。

可以通过一个参数 （可以 `-f` ？） 控制，用户自行选中指定关卡，程序仅需识别是否开启代理和蓝色作战按钮，以及之后的流程，这样更为灵活。

可提供的参考： https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/b1a75daafc87294a31b98a64e199f969fe07a4fa/Arknights/addons/combat.py#L359-L376

**Comment by Konano** [comment]
该问题已经解决。
现在如果不指定参数且启动脚本时游戏界面位于关卡的选择界面，则自动进行作战，不会重新回到主界面选择关卡。
