### ISSUE TITLE
添加对等待网络通讯界面的支持(正在提交反馈至神经)

### ISSUE THREAD

**Issue by rebelice** [Konano/arknights-mower#95]
![image](https://user-images.githubusercontent.com/20775801/151575526-36d49235-7896-4149-9b0b-611768210f55.png)

**Comment by kooWZ** [comment]
每个操作之后加一个一到两秒的sleep就行了吧

**Comment by Konano** [comment]
@kooWZ 有时候网络会卡特别久

**Comment by Konano** [comment]
See https://github.com/Konano/arknights-mower/commit/450b297610fb5a70df9188bff7824af39683d63c .
